---
name: LedFx Addon
version: 2.0.86
slug: ledfx-beta
description: A network based LED effect controller with support for advanced real-time audio effects!
url: https://github.com/mariusCZ/home-assistant-addons/tree/master/ledfx-beta
audio: true
arch:
  - aarch64
  - amd64
  - armv7
hassio_api: true
auth_api: true
ingress: true
host_network: true
host_dbus: true
ingress_stream: true
ingress_port: 0
ingress_entry: "#/./"
panel_icon: mdi:emoticon-devil-outline
panel_title: LedFx
init: false
map:
  - ssl
ports:
  80/tcp: null
ports_description:
  80/tcp: Web interface
options:
  ssl: false
  log_level: warning
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(debug|info|warning)?
  certfile: str
  keyfile: str
  ssl: bool
  leave_front_door_open: bool?
image: "ghcr.io/mariusCZ/{arch}-addon-ledfx"
